CREATE TABLE IF NOT EXISTS meusjogos (
codigo INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
codigoconcurso TEXT NOT NULL , 
tipojogo TEXT, 
num01 TEXT, 
num02 TEXT, 
num03 TEXT, 
num04 TEXT, 
num05 TEXT, 
num06 TEXT, 
num07 TEXT, 
num08 TEXT, 
num09 TEXT, 
num10 TEXT, 
num11 TEXT, 
num12 TEXT, 
num13 TEXT, 
num14 TEXT, 
num15 TEXT, 
num16 TEXT, 
num17 TEXT, 
num18 TEXT, 
num19 TEXT, 
num20 TEXT, 
num21 TEXT, 
num22 TEXT, 
num23 TEXT, 
num24 TEXT, 
num25 TEXT, 
dataregistro TEXT DEFAULT (datetime('now')) NOT NULL);