CREATE TABLE IF NOT EXISTS resultados (
codigo INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
codigoconcurso TEXT NOT NULL , 
dataconcurso TIMESTAMP NOT NULL , 
tipojogo TEXT, 
result01 TEXT, 
result02 TEXT, 
result03 TEXT, 
result04 TEXT, 
result05 TEXT, 
result06 TEXT, 
result07 TEXT, 
result08 TEXT, 
result09 TEXT, 
result10 TEXT, 
result11 TEXT, 
result12 TEXT, 
result13 TEXT, 
result14 TEXT, 
result15 TEXT, 
result16 TEXT, 
result17 TEXT, 
result18 TEXT, 
result19 TEXT, 
result20 TEXT, 
result21 TEXT, 
result22 TEXT, 
result23 TEXT, 
result24 TEXT, 
result25 TEXT, 
numganhadorespricipal INTEGER DEFAULT 0,
cidadeufprincipal TEXT,
rateioprincipal TEXT,
numganhadores02 INTEGER DEFAULT 0,
rateio02 TEXT,
numganhadores03 INTEGER DEFAULT 0,
rateio03 TEXT,
acumulado TEXT,
arrecadacao TEXT,
estimativa  TEXT,
acumuladosorteioespecial TEXT,
observacao TEXT,
dataregistro TEXT DEFAULT (datetime('now')) NOT NULL);

CREATE UNIQUE INDEX resultados_codigoconcurso_IDX ON resultados (codigoconcurso,tipojogo);